version: "3"
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./data/db:/var/lib/mysql
            - ./composer-conf/mysql-conf.d:/etc/mysql/conf.d:ro
            - ./sql:/docker-entrypoint-initdb.d
        env_file: ./composer-conf/mysql.env
